INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 1, 'Vestibulando', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 2, 'Rematrícula', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 3, 'Reingresso', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 4, 'Portador de Diploma', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 5, 'Transferência de outra Instituição', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 6, 'Transferência Interna do(s) curso(s) abaixo para', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 7, 'Transferêcia Interna de', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 8, 'Vestibulando e Trancamento', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 9, 'Matriculado e Trancado', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 10, 'Reingresso e Transferência Interna do(s) curso(s) abaixo para', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 11, 'Reingresso e Transferência Interna de', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 12, 'Reingresso e Trancamento', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 13, 'Trancamento', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 14, 'Concluiu todas as Disciplinas do Curso', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 15, 'Vestibulando Matriculado e Trancado', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 16, 'Vestibulando - Desistência de Vaga', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 17, 'Portador e Trancamento', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 19, 'Processo Seletivo - Matrícula', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 21, 'Transferência de outra Instituição e Trancamento', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 23, 'Prorrogação do Trabalho de Conclusão/Estágio', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 105, 'Transferêcia para outra Instituição', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 147, 'Vestibulando Transferência Interna de', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 148, 'Vestibulando Transferência Interna do(s) curso(s) abaixo para', true);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 175, 'Vestibulando - Não confirmação da Vaga', false);
INSERT INTO acdstateenrollbook (username, datetime, ipaddress, stateenrollbookid, description, issumtototal) VALUES ('admin', date(now()), '127.0.0.1', 24, 'Matrículas Novas CEP', false);
SELECT setval('seq_stateenrollbookid',(SELECT max(stateenrollbookid) FROM acdStateEnrollBook));
