INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 0, 'NENHUMA', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 1, 'AUDITIVA', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 2, 'FÍSICA', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 3, 'MÚLTIPLA', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 4, 'MENTAL', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 5, 'BAIXA VISÃO', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 6, 'NÃO QUERO DECLARAR', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 7, 'OUTRAS', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 8, 'CEGUEIRA', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 9, 'SURDEZ', false, false, false, NULL, NULL);
INSERT INTO basspecialnecessity (username, datetime, ipaddress, specialnecessityid, description, easyaccess, accompanimentneeds, ispermanent, howmuchweeks, begindate) VALUES ('admin', date(now()), '127.0.0.1', 10, 'SURDOCEGUEIRA', false, false, false, NULL, NULL);
SELECT setval('seq_specialnecessityid',(SELECT max(specialnecessityid) FROM basSpecialNecessity));

