<?php

/**
 * Finance close selected checks handler.
 * Contains the menus to access country registers
 *
 * @author Daniel Afonso Heisler [daniel@hsti.inf.br]
 *
 * @version $Id$
 *
 * \b Maintainers: \n
 * Alexandre Heitor Schmidt [alexsmith@solis.coop.br]
 * Daniel Afonso Heisler [daniel@solis.coop.br]
 * Jamiel Spezia [jamiel@solis.coop.br]
 * William Prigol Lopes [william@solis.coop.br]
 *
 * @since
 * Class created on 30/10/2007
 *
 * \b Organization: \n
 * SOLIS - Cooperativa de Solucoes Livres \n
 * The SAGU2 Development Team
 *
 * \b CopyLeft: \n
 * CopyLeft (L) 2005 SOLIS - Cooperativa de Solucoes Livres \n
 *
 * \b License: \n
 * Licensed under GPL (for further details read the COPYING file or http://www.gnu.org/copyleft/gpl.html )
 *
 * \b History: \n
 * See history in CVS repository: http://sagu.solis.coop.br
 *
 **/

$MIOLO->trace('file:' . $_SERVER['SCRIPT_NAME']);
$MIOLO->checkAccess($module, FIN_ACCESS, true, true);

$home     = 'main:register:closeAllChecks';
$navbar->addOption(_M('Close selected checks', $module), $module, $home);

$function = MIOLO::_request('function');
$MIOLO->checkAccess($module, FIN_INSERT, true, true);

$ui       = $MIOLO->getUI();
$frmCheck = $ui->getForm( $module, 'FrmCloseSelectedChecks' );

$theme->clearContent($frmCheck);
$theme->insertContent($frmCheck);

?>
